language: node_js
node_js: 
  - "stable"
cache:
  directories:
  - "$HOME/.npm"
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'root';" -U postgres 
script: npm test