before_script: 
  - "psql -c \"CREATE DATABASE teamwork;\" -U postgres"
cache:
  directories:
    - node_modules
language: node_js
node_js: 
  - stable
env:
  - NODE_ENV=ci PORT=8080
services: 
  - postgresql
script:
  - npm run test
