language: node_js
node_js: 
  - "stable"
cache:
  directories:
  - "$HOME/.npm"
services:
  - postgresql
env:
  - DB=postgres://postgres@localhost/teamwork
  before_script:
  - psql -c "CREATE DATABASE teamwork;" -U postgres 
script: npm test